server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy vers le backend externe
    # On remplace l'Origin par celui du backend pour éviter les blocages CORS
    location /api/ {
        proxy_pass         https://asapbackend.kikandi.com/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              asapbackend.kikandi.com;
        proxy_set_header   Origin            https://asapbackend.kikandi.com;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
    }

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
